### ISSUE TITLE
[Bug] Promotion pieces not updating properly 

### ISSUE THREAD

**Issue by verity-cook** [uco16/chess#3]
After promotion to bishop or knight piece in FEN is "undefined". 
before promotion: "r1bqkbR1/2pppp1P/n4n2/8/8/2N5/pqPPPP2/2BQKBNR/ w KQkq - 3 15"
after promotion: "r1bqkbRundefined/2pppp2/n4n2/8/8/2N5/1qPPPP2/p1BQKBNR/ w KQkq - 0 16"
should be "r1bqkbRB/2pppp2/n4n2/8/8/2N5/1qPPPP2/p1BQKBNR/ w KQkq - 0 16"

FEN string prints before promotion, should print afterwards.

**Comment by uco16** [comment]
Fixed in commit 53d69ac88d7605cecb0046544b81dcbe45ed66cb.
