### ISSUE TITLE
[Bug] Enter issue title

### ISSUE THREAD

**Issue by verity-cook** [uco16/chess#4]
**Describe the bug**
Ein passiont not working

**To Reproduce**
1. r1bqkb1r/ppp2p1p/2n5/3ppPp1/4n3/3B2PN/PPPP3P/RNBQK2R/ w KQkq g6 0 8 

**Expected behavior**
Ein passoint

**Comment by uco16** [comment]
Fixed in fcca20e41d814e0796d26e073e82873edc07aa32.
