### ISSUE TITLE
Pawn and Knight patterns are wrong

### ISSUE THREAD

**Issue by verity-cook** [uco16/chess#5]
**Describe the bug**
Pawns can move to any square as long it is not occupied by a square of the same colour. Knights can move 3 squares horizontally or vertically as well as their usual pattern.

**To Reproduce**
1. start new game with a partner
2. move a pawn to where ever you want 
3. Move a knight 3 square up/down or left/right

**Expected behavior**
Usual pawn pattern and knight pattern 

**Screenshots**
![image](https://user-images.githubusercontent.com/47567215/127020644-2efa5eaf-a639-4d0d-bd55-c55dac07cc36.png)

**Comment by uco16** [comment]
Pawn issue fixed in 21a9f4050c4ef3fe46390c4dcfe60100866acdf3.

**Comment by uco16** [comment]
Knight issue fixed in 11a4e3a6f0611e4cd8563a26bda84a5facb7f3ef.
